repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      ethis testanguage_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0  # Use the ref you want to point at
    hooks:        
    - id: check-json
    - id: flake8
    - id: detect-private-key 
    - id: pretty-format-json 
      args: ['--autofix', '--no-sort-keys']
    - id: check-yaml
